version: "3.9"

services:
  # Proxy reverso com geração automática de certificados Let's Encrypt
  nginx-proxy:
    profiles: ["prod"]
    image: nginxproxy/nginx-proxy:1.6-alpine
    ports:
      - "80:80"
      - "443:443"
    environment:
      - DEFAULT_HOST=${APP_DOMAIN}
      - ENABLE_IPV6=${ENABLE_IPV6:-false}
    volumes:
      - nginx_certs:/etc/nginx/certs
      - nginx_vhost:/etc/nginx/vhost.d
      - nginx_html:/usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro
    restart: unless-stopped
    networks:
      - proxy

  nginx-proxy-acme:
    profiles: ["prod"]
    image: nginxproxy/acme-companion:2.4
    depends_on:
      - nginx-proxy
    environment:
      - NGINX_PROXY_CONTAINER=nginx-proxy
      - DEFAULT_EMAIL=${LETSENCRYPT_EMAIL}
      - ACME_CA_URI=${ACME_CA_URI:-https://acme-v02.api.letsencrypt.org/directory}
    volumes:
      - nginx_certs:/etc/nginx/certs
      - nginx_vhost:/etc/nginx/vhost.d
      - nginx_html:/usr/share/nginx/html
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: unless-stopped
    networks:
      - proxy

  # Produção do frontend (build + serve estático atrás do proxy)
  web:
    profiles: ["prod"]
    build:
      context: .
      dockerfile: docker/frontend.Dockerfile
    environment:
      # Opcional: defina variáveis VITE_* caso adapte o client do Supabase para usar import.meta.env
      # - VITE_SUPABASE_URL=
      # - VITE_SUPABASE_ANON_KEY=
      - NODE_ENV=production
      - VIRTUAL_HOST=${APP_DOMAIN}
      - VIRTUAL_PORT=80
      - LETSENCRYPT_HOST=${APP_DOMAIN}
      - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL}
    expose:
      - "80"
    restart: unless-stopped
    networks:
      - proxy

  # Desenvolvimento do frontend (hot-reload)
  web-dev:
    profiles: ["dev"]
    image: node:20-alpine
    working_dir: /app
    command: sh -c "npm ci && npm run dev -- --host 0.0.0.0 --port 5173"
    ports:
      - "5173:5173" # Acesse em http://localhost:5173
    environment:
      - NODE_ENV=development
      # Opcional: defina variáveis VITE_* caso adapte o client do Supabase para usar import.meta.env
      # - VITE_SUPABASE_URL=
      # - VITE_SUPABASE_ANON_KEY=
    volumes:
      - ./:/app
      - /app/node_modules

volumes:
  nginx_certs:
  nginx_vhost:
  nginx_html:

networks:
  proxy:
